#!/usr/bin/env bats
# TP2.T5 — xfail integration test: end-to-end Phase-2 ingest+render against full fixture corpus
#
# guards T.P2.5 acceptance gate:
#   "Duong can click 'Evelynn / Sona' on the home page and reach a populated coordinator-detail page."
#
# Plan-Ref: plans/approved/personal/2026-04-25-retrospection-dashboard-and-canonical-v1.md
#
# xfail: skipped if tools/retro/render.mjs is missing (T.P2.5 not yet landed).
# TODO (T.P2.5): implement coordinator-detail HTML page + home-page Phase-2 tile integration,
#   then flip skip.
#
# DoD checks:
#   (c) dist/data/feedback-rollup.json, decision-rollup.json, coordinator-weekly.json exist and deep-equal goldens
#   (d) dist/coordinator-evelynn-week-<iso>.html carries ratio panel, histograms, match-rate table
#   (e) dist/index.html carries feedback open-entries tile AND lowest-match-rate-axes tile
#   (f) Phase-1 plan-<slug>.html pages are byte-identical to Phase-1 baseline (regression invariant)
#   (g) total wall time <8s
#
# POSIX-portable: no find -printf, no GNU sed -i '', no readarray.
# Requires: node >= 18, bats, duckdb CLI on PATH.

RETRO_ROOT="$(cd "$(dirname "$BATS_TEST_FILENAME")/.." && pwd)"
FIXTURES_DIR="$RETRO_ROOT/fixtures/e2e-phase2"
QUERIES_DIR="$RETRO_ROOT/queries"
INGEST_PATH="$RETRO_ROOT/ingest.mjs"
RENDER_PATH="$RETRO_ROOT/render.mjs"

# Phase-1 regression baseline — the plan-<slug>.html generated by Phase 1
PHASE1_BASELINE_DIR="$RETRO_ROOT/fixtures/e2e-phase2/phase1-baseline"

# ---------------------------------------------------------------------------
# xfail guard — skip entire suite if render.mjs or Phase-2 queries are absent
# ---------------------------------------------------------------------------
setup_file() {
  if [ ! -f "$RENDER_PATH" ]; then
    skip "xfail: render.mjs not yet implemented (TODO T.P2.5)"
  fi
  if [ ! -f "$INGEST_PATH" ]; then
    skip "xfail: ingest.mjs not yet implemented (TODO T.P1.2)"
  fi
  # Phase-2 queries must exist
  if [ ! -f "$QUERIES_DIR/feedback-rollup.sql" ]; then
    skip "xfail: feedback-rollup.sql not yet implemented (TODO T.P2.2)"
  fi
  if [ ! -f "$QUERIES_DIR/decision-rollup.sql" ]; then
    skip "xfail: decision-rollup.sql not yet implemented (TODO T.P2.3)"
  fi
  if [ ! -f "$QUERIES_DIR/coordinator-weekly.sql" ]; then
    skip "xfail: coordinator-weekly.sql not yet implemented (TODO T.P2.4)"
  fi
}

# ---------------------------------------------------------------------------
# setup — seed Phase-2 fixture HOME (Phase-1 corpus + feedback + decisions + prompt-stats session)
# ---------------------------------------------------------------------------
setup() {
  TMP_DIR="$(mktemp -d /tmp/retro-e2e-p2-XXXXXX)"
  export HOME="$TMP_DIR/fake-home"
  export STRAWBERRY_USAGE_CACHE="$TMP_DIR/strawberry-usage-cache"
  export RETRO_GIT_LOG_MOCK="$FIXTURES_DIR/git-log-e2e-phase2.json"

  # Seed Phase-1 corpus (parent session, subagents, sentinels)
  SESS_DIR="$HOME/.claude/projects/strawberry-agents/sess-e2e-parent/subagents"
  mkdir -p "$SESS_DIR"
  mkdir -p "$STRAWBERRY_USAGE_CACHE/subagent-sentinels"

  cp "$FIXTURES_DIR/parent-session-with-prompts.jsonl" \
     "$HOME/.claude/projects/strawberry-agents/sess-e2e-parent/sess-e2e-parent.jsonl"
  cp "$FIXTURES_DIR/subagents/agent-e2e-p2-001.jsonl" "$SESS_DIR/"
  cp "$FIXTURES_DIR/subagents/agent-e2e-p2-001.meta.json" "$SESS_DIR/"
  cp "$FIXTURES_DIR/subagent-sentinels/agent-e2e-p2-001" \
     "$STRAWBERRY_USAGE_CACHE/subagent-sentinels/"

  # Seed feedback/INDEX.md
  FEEDBACK_DIR="$TMP_DIR/strawberry-app/feedback"
  mkdir -p "$FEEDBACK_DIR"
  cp "$FIXTURES_DIR/feedback-index.md" "$FEEDBACK_DIR/INDEX.md"

  # Seed decision logs
  DECISIONS_DIR="$TMP_DIR/strawberry-agents/agents/evelynn/memory/decisions"
  mkdir -p "$DECISIONS_DIR"
  cp "$FIXTURES_DIR/decisions/evelynn/2026-04-01-routing-high.md" "$DECISIONS_DIR/"
  cp "$FIXTURES_DIR/decisions/evelynn/2026-04-15-routing-medium.md" "$DECISIONS_DIR/"
  cp "$FIXTURES_DIR/decisions/evelynn/2026-04-20-routing-silent.md" "$DECISIONS_DIR/"

  EVENTS_PATH="$STRAWBERRY_USAGE_CACHE/events.jsonl"
  DIST_DIR="$TMP_DIR/dist"
  mkdir -p "$DIST_DIR/data"
}

teardown() {
  rm -rf "$TMP_DIR"
}

# ---------------------------------------------------------------------------
# Test (c): all three Phase-2 JSON outputs exist and deep-equal their goldens
# ---------------------------------------------------------------------------
@test "retro:ingest+render produces dist/data/feedback-rollup.json" {
  node "$INGEST_PATH" --cache-dir "$STRAWBERRY_USAGE_CACHE"
  node "$RENDER_PATH" --events "$EVENTS_PATH" --queries-dir "$QUERIES_DIR" --out-dir "$DIST_DIR"
  [ -f "$DIST_DIR/data/feedback-rollup.json" ]
}

@test "feedback-rollup.json deep-equals its golden expected.json" {
  node "$INGEST_PATH" --cache-dir "$STRAWBERRY_USAGE_CACHE"
  node "$RENDER_PATH" --events "$EVENTS_PATH" --queries-dir "$QUERIES_DIR" --out-dir "$DIST_DIR"
  node -e "
    const a = require('$DIST_DIR/data/feedback-rollup.json');
    const b = require('$QUERIES_DIR/feedback-rollup.expected.json');
    const as = JSON.stringify(a.map(r=>Object.fromEntries(Object.entries(r).sort())).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))));
    const bs = JSON.stringify(b.map(r=>Object.fromEntries(Object.entries(r).sort())).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))));
    if (as !== bs) { console.error('feedback-rollup.json does not match golden'); process.exit(1); }
  "
}

@test "retro:ingest+render produces dist/data/decision-rollup.json" {
  node "$INGEST_PATH" --cache-dir "$STRAWBERRY_USAGE_CACHE"
  node "$RENDER_PATH" --events "$EVENTS_PATH" --queries-dir "$QUERIES_DIR" --out-dir "$DIST_DIR"
  [ -f "$DIST_DIR/data/decision-rollup.json" ]
}

@test "retro:ingest+render produces dist/data/coordinator-weekly.json" {
  node "$INGEST_PATH" --cache-dir "$STRAWBERRY_USAGE_CACHE"
  node "$RENDER_PATH" --events "$EVENTS_PATH" --queries-dir "$QUERIES_DIR" --out-dir "$DIST_DIR"
  [ -f "$DIST_DIR/data/coordinator-weekly.json" ]
}

# ---------------------------------------------------------------------------
# Test (d): coordinator-detail HTML contains required elements
# ---------------------------------------------------------------------------
@test "dist/coordinator-evelynn-week-*.html exists after Phase-2 render" {
  node "$INGEST_PATH" --cache-dir "$STRAWBERRY_USAGE_CACHE"
  node "$RENDER_PATH" --events "$EVENTS_PATH" --queries-dir "$QUERIES_DIR" --out-dir "$DIST_DIR"
  # Match at least one coordinator detail page for evelynn
  coordinator_page="$(ls "$DIST_DIR"/coordinator-evelynn-week-*.html 2>/dev/null | head -1)"
  [ -n "$coordinator_page" ]
}

@test "coordinator-detail HTML contains inline-vs-delegate ratio panel" {
  node "$INGEST_PATH" --cache-dir "$STRAWBERRY_USAGE_CACHE"
  node "$RENDER_PATH" --events "$EVENTS_PATH" --queries-dir "$QUERIES_DIR" --out-dir "$DIST_DIR"
  coordinator_page="$(ls "$DIST_DIR"/coordinator-evelynn-week-*.html 2>/dev/null | head -1)"
  [ -n "$coordinator_page" ]
  grep -q "delegate_ratio\|delegate-ratio\|delegation-ratio" "$coordinator_page"
}

@test "coordinator-detail HTML contains per-axis match-rate table" {
  node "$INGEST_PATH" --cache-dir "$STRAWBERRY_USAGE_CACHE"
  node "$RENDER_PATH" --events "$EVENTS_PATH" --queries-dir "$QUERIES_DIR" --out-dir "$DIST_DIR"
  coordinator_page="$(ls "$DIST_DIR"/coordinator-evelynn-week-*.html 2>/dev/null | head -1)"
  [ -n "$coordinator_page" ]
  grep -q "match_rate\|match-rate" "$coordinator_page"
}

@test "coordinator-detail HTML contains histogram SVG canvases for prompt stats" {
  node "$INGEST_PATH" --cache-dir "$STRAWBERRY_USAGE_CACHE"
  node "$RENDER_PATH" --events "$EVENTS_PATH" --queries-dir "$QUERIES_DIR" --out-dir "$DIST_DIR"
  coordinator_page="$(ls "$DIST_DIR"/coordinator-evelynn-week-*.html 2>/dev/null | head -1)"
  [ -n "$coordinator_page" ]
  grep -q "<svg" "$coordinator_page"
}

# ---------------------------------------------------------------------------
# Test (e): index.html carries Phase-2 tiles
# ---------------------------------------------------------------------------
@test "dist/index.html contains feedback open-entries tile after Phase-2 render" {
  node "$INGEST_PATH" --cache-dir "$STRAWBERRY_USAGE_CACHE"
  node "$RENDER_PATH" --events "$EVENTS_PATH" --queries-dir "$QUERIES_DIR" --out-dir "$DIST_DIR"
  grep -q "feedback\|open-entries\|open_count" "$DIST_DIR/index.html"
}

@test "dist/index.html contains lowest-match-rate-axes tile after Phase-2 render" {
  node "$INGEST_PATH" --cache-dir "$STRAWBERRY_USAGE_CACHE"
  node "$RENDER_PATH" --events "$EVENTS_PATH" --queries-dir "$QUERIES_DIR" --out-dir "$DIST_DIR"
  grep -q "match.rate\|match-rate\|lowest.*axis\|axis.*match" "$DIST_DIR/index.html"
}

# ---------------------------------------------------------------------------
# Test (f): Phase-1 plan-<slug>.html pages are byte-identical to Phase-1 baseline (regression)
# ---------------------------------------------------------------------------
@test "Phase-1 plan HTML page is byte-identical to Phase-1 baseline after Phase-2 render" {
  node "$INGEST_PATH" --cache-dir "$STRAWBERRY_USAGE_CACHE"
  node "$RENDER_PATH" --events "$EVENTS_PATH" --queries-dir "$QUERIES_DIR" --out-dir "$DIST_DIR"
  p1_slug="2026-04-21-agent-feedback-system"
  p1_actual="$DIST_DIR/plan-${p1_slug}.html"
  p1_baseline="$PHASE1_BASELINE_DIR/plan-${p1_slug}.html"
  [ -f "$p1_actual" ]
  if [ -f "$p1_baseline" ]; then
    diff -q "$p1_actual" "$p1_baseline" || {
      echo "Phase-1 plan HTML changed after Phase-2 render (regression)"
      return 1
    }
  fi
}

# ---------------------------------------------------------------------------
# Test (g): total wall time <8s
# ---------------------------------------------------------------------------
@test "Phase-2 end-to-end pipeline completes in under 8 seconds on fixture corpus" {
  start_ts="$(date +%s)"
  node "$INGEST_PATH" --cache-dir "$STRAWBERRY_USAGE_CACHE"
  node "$RENDER_PATH" --events "$EVENTS_PATH" --queries-dir "$QUERIES_DIR" --out-dir "$DIST_DIR"
  end_ts="$(date +%s)"
  elapsed="$((end_ts - start_ts))"
  [ "$elapsed" -lt 8 ]
}
