#!/usr/bin/env bash
# tests/ci/test_pr_lint_no_ai_attribution.sh
#
# T5 — xfail: shell-level test of the PR body/comment AI-marker lint helper.
#
# Plan: plans/approved/personal/2026-04-25-no-ai-attribution-defense-in-depth.md T5
# Extended: plans/approved/personal/2026-04-26-no-ai-attribution-detector-tightening.md T1
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"

HELPER="$REPO_ROOT/scripts/ci/pr-lint-no-ai-attribution.sh"

if [ ! -f "$HELPER" ]; then
  printf 'FAIL: helper not found: %s\n' "$HELPER" >&2
  exit 1
fi

pass=0
fail=0
xfail=0   # known failures before T2 impl lands

run_case() {
  local desc="$1"
  local body="$2"
  local expect_exit="$3"

  actual_exit=0
  printf '%s' "$body" | bash "$HELPER" >/dev/null 2>&1 || actual_exit=$?

  if [ "$actual_exit" -eq "$expect_exit" ]; then
    printf 'PASS: %s\n' "$desc"
    pass=$((pass + 1))
  else
    printf 'FAIL: %s (expected exit %d, got %d)\n' "$desc" "$expect_exit" "$actual_exit" >&2
    fail=$((fail + 1))
  fi
}

# xfail wrapper — expected to fail before T2 lands.
# Plan: no-ai-attribution-detector-tightening
run_xfail() {
  local desc="$1"
  local body="$2"
  local expect_exit="$3"

  actual_exit=0
  printf '%s' "$body" | bash "$HELPER" >/dev/null 2>&1 || actual_exit=$?

  if [ "$actual_exit" -eq "$expect_exit" ]; then
    printf 'XPASS: %s\n' "$desc"
    pass=$((pass + 1))
  else
    printf 'XFAIL (expected before impl): %s\n' "$desc"
    xfail=$((xfail + 1))
  fi
}

# --- Cases that must PASS (exit 0) ---

run_case "Clean PR body" \
  "## Summary
- Fixed the widget" \
  0

# --- QA Plan pass cases (plan: no-ai-attribution-detector-tightening) ---

# Pass case 1: bare "sonnet-high" tier mention
run_xfail "QA-P1: Viktor (sonnet-high) — bare tier mention must pass" \
  "## Summary
Viktor (sonnet-high) implemented the worktree guard." \
  0

# Pass case 2: opus model selection — bare mention
run_xfail "QA-P2: opus model selection — bare mention must pass" \
  "## Summary
Updated agent def for opus model selection." \
  0

# Pass case 3: Sonnet executors routing — bare technical ref
run_xfail "QA-P3: Sonnet executors routing — bare technical ref must pass" \
  "## Summary
Promotes plan via Orianna; routes through Sonnet executors." \
  0

# Pass case 4: Anthropic's API — possessive technical reference
run_xfail "QA-P4: Anthropic's tool-use API — possessive ref must pass" \
  "## Summary
Anthropic's tool-use API supports streaming." \
  0

# Pass case 5: the Claude CLI — no attribution verb
run_xfail "QA-P5: The Claude CLI — bare mention, no attribution verb, must pass" \
  "## Summary
The Claude CLI prompts for confirmation." \
  0

# Pass case 6: Human-Verified: yes alone with clean body — inert, must pass
run_case "QA-P6: Human-Verified: yes with clean body — inert text, must pass" \
  "## Summary
- clean change
Human-Verified: yes" \
  0

# --- Cases that must FAIL (exit 1) ---

run_case "Body containing robot emoji + Generated with Claude Code" \
  "## Summary
🤖 Generated with [Claude Code](https://claude.com/code)" \
  1

run_case "Body containing Co-Authored-By trailer (universal block)" \
  "## Summary
Co-Authored-By: Anyone <a@b>" \
  1

run_case "Comment: reviewed by Sonnet 4.6 — bare mention, no attr verb, now passes" \
  "This PR was reviewed by Sonnet 4.6" \
  0

# F1 adversarial: prefix chars — behavior changes with attribution-phrase detector.
# Bare mentions without attribution verbs now pass.
run_case "F1: (Sonnet) in PR body — bare mention, now passes" \
  "## Summary
Built with (Sonnet) model" \
  0

run_case "F1: [Opus] in PR body — bare mention, now passes" \
  "## Summary
Using [Opus] here" \
  0

run_case "F1: :Claude in PR body — bare mention, now passes" \
  "## Summary
model:Claude was used" \
  0

# F2 adversarial: "Written by Sonnet4.6" still blocks (phrase match); bare Opus4 passes.
run_case "F2: Written by Sonnet4.6 in PR body — phrase regex matches, blocks" \
  "## Summary
Written by Sonnet4.6" \
  1

run_case "F2: Opus4 in PR body — bare mention, now passes" \
  "## Summary
Using Opus4" \
  0

# --- QA Plan fail cases (plan: no-ai-attribution-detector-tightening) ---

# Fail case 1: Co-Authored-By with AI email
run_case "QA-F1: Co-Authored-By Claude noreply@anthropic.com" \
  "## Summary
Co-Authored-By: Claude Opus 4.7 <noreply@anthropic.com>" \
  1

# Fail case 2: Co-Authored-By any non-AI name (universal block)
run_case "QA-F2: Co-Authored-By non-AI name (universal block)" \
  "## Summary
Co-Authored-By: Anybody Else <x@y.test>" \
  1

# Fail case 3: robot emoji
run_case "QA-F3: robot emoji in body" \
  "🤖 Generated with [Claude Code]" \
  1

# Fail case 4: claude.com/code URL
run_case "QA-F4: claude.com/code URL in body" \
  "## Summary
See https://claude.com/code for details" \
  1

# Fail case 5: "Generated by Claude" — attribution phrase
run_case "QA-F5: Generated by Claude — attribution phrase" \
  "## Summary
Generated by Claude" \
  1

# Fail case 6: "Authored by Sonnet" — attribution phrase
run_case "QA-F6: Authored by Sonnet — attribution phrase" \
  "## Summary
Authored by Sonnet" \
  1

# Fail case 7: "Written by Anthropic"
run_case "QA-F7: Written by Anthropic — attribution phrase" \
  "## Summary
Written by Anthropic" \
  1

# Fail case 8: "Co-authored by Opus"
run_case "QA-F8: Co-authored by Opus — attribution phrase" \
  "## Summary
Co-authored by Opus" \
  1

# Fail case 9: "Implemented by Claude." — trailing attribution
run_case "QA-F9: Implemented by Claude. — trailing attribution" \
  "## Summary
Implemented by Claude." \
  1

# Fail case 10: email domain match
run_case "QA-F10: anthropic.com email in PR body" \
  "## Summary
Contact <x@anthropic.com>" \
  1

# --- Override-no-op regression cases (plan: no-ai-attribution-detector-tightening) ---

# Case 11: attribution phrase + Human-Verified: yes → still blocks after T2
run_xfail "QA-C11: Generated by Claude + Human-Verified: yes — override removed, must still block" \
  "## Summary
Generated by Claude
Human-Verified: yes" \
  1

# Case 12: Co-Authored-By + Human-Verified: yes → still blocks after T2
run_xfail "QA-C12: Co-Authored-By + Human-Verified: yes — override removed, must still block" \
  "## Summary
Co-Authored-By: Foo <a@b>
Human-Verified: yes" \
  1

# --- Summary ---

printf '\nT5+T1ext: %d passed, %d failed, %d xfail (expected before impl)\n' "$pass" "$fail" "$xfail"
if [ "$fail" -gt 0 ]; then
  exit 1
fi
exit 0
