#!/usr/bin/env bash
# scripts/ci/pr-lint-no-ai-attribution.sh
#
# Scans PR body or comment text (passed via stdin) for AI attribution markers.
# Used by .github/workflows/pr-lint.yml (pr-no-ai-attribution job).
#
# Plans:
#   plans/approved/personal/2026-04-25-no-ai-attribution-defense-in-depth.md T6
#   plans/approved/personal/2026-04-26-no-ai-attribution-detector-tightening.md T2
#
# Rules (from _shared/no-ai-attribution.md, non-exhaustive):
#   - Co-Authored-By: trailer (universal block)
#   - AI email domains: @anthropic.com, @claude.com, @noreply.anthropic.com
#   - Verbatim: AI-generated, 🤖, Generated with [Claude Code], claude.com/code
#   - Attribution phrases: "Generated by Claude", "Authored by Sonnet", etc.
#   - Trailing attribution: "by Claude" / "by Anthropic" at end-of-line or before .,;
#
# Bare technical mentions of model names are allowed.
# No override mechanism. Human-Verified: yes is inert text (ignored).
#
# Usage:
#   printf '%s' "$PR_BODY" | bash scripts/ci/pr-lint-no-ai-attribution.sh
#
# Exit codes:
#   0 — clean
#   1 — AI attribution marker found

set -uo pipefail

# Read stdin into a temp file for multi-pass scanning
tmpfile="$(mktemp)"
trap 'rm -f "$tmpfile"' EXIT INT TERM HUP
cat > "$tmpfile"

offending=""

# Co-Authored-By: trailer (any name)
coauthor="$(grep -iE '^Co-Authored-By:' "$tmpfile" 2>/dev/null || true)"
[ -n "$coauthor" ] && offending="$offending
$coauthor"

# AI email domains
domains="$(grep -iE '@(anthropic\.com|claude\.com|noreply\.anthropic\.com)' "$tmpfile" 2>/dev/null || true)"
[ -n "$domains" ] && offending="$offending
$domains"

# Verbatim unambiguous markers
# Tightened: claude.com -> claude\.com/code
verbatim="$(grep -iE '🤖|Generated with \[Claude Code\]|claude\.com/code|AI-generated' "$tmpfile" 2>/dev/null || true)"
[ -n "$verbatim" ] && offending="$offending
$verbatim"

# Attribution-phrase regexes (replaces bare-token body_markers)
# Verb + model name (case-insensitive)
phrases="$(grep -iE '(Generated|Authored|Written|Co-authored|Coauthored)[[:space:]]+by[[:space:]]+(Claude|Anthropic|Sonnet|Opus|Haiku)' "$tmpfile" 2>/dev/null || true)"
[ -n "$phrases" ] && offending="$offending
$phrases"

# Narrow trailing-attribution form: "by Claude" / "by Anthropic" at EOL or before .,;
trailing="$(grep -iE '(^|[[:space:]])[Bb]y[[:space:]]+(Claude|Anthropic)([[:space:]]*[.,;]|[[:space:]]*$)' "$tmpfile" 2>/dev/null || true)"
[ -n "$trailing" ] && offending="$offending
$trailing"

# Deduplicate
offending="$(printf '%s\n' "$offending" | grep -v '^[[:space:]]*$' | sort -u || true)"

if [ -z "$offending" ]; then
  exit 0
fi

printf '\n✘ AI attribution marker detected in PR body or comment:\n' >&2
while IFS= read -r line; do
  [ -n "$line" ] && printf '    %s\n' "$line" >&2
done <<EOF
$offending
EOF

cat >&2 <<'REJECTION'

Per _shared/no-ai-attribution.md (non-exhaustive marker list):
  - No Co-Authored-By: trailers in PR body or comments.
  - No AI attribution phrases: "Generated by Claude", "Authored by Sonnet",
    "Written by Anthropic", "Co-authored by Opus", "by Claude", etc.
  - No verbatim markers: AI-generated, 🤖, "Generated with [Claude Code]",
    claude.com/code.

Bare technical mentions of model names are allowed.
Remove the offending attribution content and retry.
REJECTION

exit 1
