#!/usr/bin/env bash
# tests/hooks/test_commit_msg_no_ai_coauthor.sh
#
# T3 — xfail: regression + new-coverage tests for commit-msg-no-ai-coauthor.sh
#
# Plan: plans/approved/personal/2026-04-25-no-ai-attribution-defense-in-depth.md T3
# Extended: plans/approved/personal/2026-04-26-no-ai-attribution-detector-tightening.md T1
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"

HOOK="$REPO_ROOT/scripts/hooks/commit-msg-no-ai-coauthor.sh"

if [ ! -f "$HOOK" ]; then
  printf 'FAIL: hook not found: %s\n' "$HOOK" >&2
  exit 1
fi

pass=0
fail=0
xfail=0   # known failures before T2 impl lands
xpass=0   # xfail that unexpectedly passes (still counted correct)

run_case() {
  local desc="$1"
  local msg="$2"
  local expect_exit="$3"  # 0=pass 1=reject

  tmpfile="$(mktemp)"
  printf '%s\n' "$msg" > "$tmpfile"
  actual_exit=0
  bash "$HOOK" "$tmpfile" >/dev/null 2>&1 || actual_exit=$?
  rm -f "$tmpfile"

  if [ "$actual_exit" -eq "$expect_exit" ]; then
    printf 'PASS: %s\n' "$desc"
    pass=$((pass + 1))
  else
    printf 'FAIL: %s (expected exit %d, got %d)\n' "$desc" "$expect_exit" "$actual_exit" >&2
    fail=$((fail + 1))
  fi
}

# xfail wrapper — expected to fail BEFORE T2 lands; direction check only.
# Plan: no-ai-attribution-detector-tightening
run_xfail() {
  local desc="$1"
  local msg="$2"
  local expect_exit="$3"  # what it SHOULD be after T2

  tmpfile="$(mktemp)"
  printf '%s\n' "$msg" > "$tmpfile"
  actual_exit=0
  bash "$HOOK" "$tmpfile" >/dev/null 2>&1 || actual_exit=$?
  rm -f "$tmpfile"

  if [ "$actual_exit" -eq "$expect_exit" ]; then
    # xfail that already passes — count as pass (impl may already be in)
    printf 'XPASS: %s\n' "$desc"
    xpass=$((xpass + 1))
    pass=$((pass + 1))
  else
    printf 'XFAIL (expected before impl): %s\n' "$desc"
    xfail=$((xfail + 1))
  fi
}

# --- Cases that must REJECT (exit 1) ---

# Current gap — would have caught b2b8944
run_case "Co-Authored-By: Claude Sonnet 4.6 noreply@anthropic.com" \
  "chore: some work

Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>" \
  1

run_case "Co-Authored-By: Claude Opus 4.7 noreply@anthropic.com" \
  "chore: some work

Co-Authored-By: Claude Opus 4.7 <noreply@anthropic.com>" \
  1

# Universal block — any name in Co-Authored-By
run_case "Co-Authored-By: Random Human human@example.com (universal block)" \
  "chore: some work

Co-Authored-By: Random Human <human@example.com>" \
  1

# Body markers
run_case "Body containing robot emoji + Generated with Claude Code" \
  "chore: some work

🤖 Generated with [Claude Code](https://claude.com/code)" \
  1

run_case "Body containing AI-generated commit message" \
  "chore: some work

AI-generated commit message" \
  1

run_case "Body containing bare URL claude.com/code" \
  "chore: some work

See claude.com/code for details" \
  1

run_case "Body mentioning Sonnet 4.6 (model name is a marker)" \
  "chore: some work

This was written by Sonnet 4.6 model" \
  1

# F1 adversarial: prefix chars — behavior changes with attribution-phrase detector.
# Bare mentions without attribution verbs now pass (new detection rules).
# Only "by Claude/Anthropic" trailing form still blocks.
run_case "F1: (Sonnet) in body — bare mention, now passes (no attribution verb)" \
  "chore: some work

Built with (Sonnet) model" \
  0

run_case "F1: [Opus] in body — bare mention, now passes (no attribution verb)" \
  "chore: some work

Using [Opus] here" \
  0

run_case "F1: :Sonnet in body — bare mention, now passes (no attribution verb)" \
  "chore: some work

model:Sonnet was used" \
  0

run_case "F1: Powered by \"Claude\" assistant — not at EOL/punct, now passes" \
  'chore: some work

Powered by "Claude" assistant' \
  0

# F2 adversarial: marker glued to digit — bare mentions now pass.
# "Written by Sonnet4.6" still blocks because "Written by Sonnet" matches phrase regex.
run_case "F2: Sonnet4.6 in body — Written by Sonnet4.6 matches phrase regex, blocks" \
  "chore: some work

Written by Sonnet4.6 model" \
  1

run_case "F2: Opus4 in body — bare mention, now passes (no attribution verb)" \
  "chore: some work

Using Opus4 here" \
  0

run_case "F2: Claude4 in body — bare mention, now passes (no attribution verb)" \
  "chore: some work

Claude4 wrote this" \
  0

# --- QA Plan fail cases (plan: no-ai-attribution-detector-tightening) ---
# These assert attribution-phrase detection specifically.

# Fail case 5: "Generated by Claude" (attribution phrase)
run_case "QA-F5: Generated by Claude (attribution phrase)" \
  "chore: some work

Generated by Claude" \
  1

# Fail case 6: "Authored by Sonnet" (attribution phrase, model name)
run_case "QA-F6: Authored by Sonnet (attribution phrase)" \
  "chore: some work

Authored by Sonnet" \
  1

# Fail case 7: "Written by Anthropic"
run_case "QA-F7: Written by Anthropic (attribution phrase)" \
  "chore: some work

Written by Anthropic" \
  1

# Fail case 8: "Co-authored by Opus"
run_case "QA-F8: Co-authored by Opus (attribution phrase)" \
  "chore: some work

Co-authored by Opus" \
  1

# Fail case 9: "Implemented by Claude." (trailing-attribution form — period after)
run_case "QA-F9: Implemented by Claude. (trailing attribution)" \
  "chore: some work

Implemented by Claude." \
  1

# Fail case 10: AI email domain match
run_case "QA-F10: email domain anthropic.com in body" \
  "chore: some work

Contact <x@anthropic.com> for details" \
  1

# --- Cases that must PASS (exit 0) ---

run_case "Clean message with no trailer" \
  "chore: fix the build" \
  0

# False-positive guard: word 'maintain' contains 'ai' — must not be blocked
run_case "Word 'maintain' does not trigger AI-marker scan" \
  "fix: maintain backward compat" \
  0

# --- QA Plan pass cases (plan: no-ai-attribution-detector-tightening) ---
# These assert bare technical mentions are NOT blocked post-T2.

# Pass case 1: bare "sonnet-high" tier mention
run_xfail "QA-P1: Viktor (sonnet-high) in body — bare tier mention must pass" \
  "chore: some work

Viktor (sonnet-high) implemented the worktree guard." \
  0

# Pass case 2: subject line mentioning opus model selection
run_xfail "QA-P2: chore subject with opus — bare model-tier mention must pass" \
  "chore: update agent def for opus model selection" \
  0

# Pass case 3: body mentioning Sonnet executors in routing context
run_xfail "QA-P3: Sonnet executors routing mention — bare technical ref must pass" \
  "chore: promote plan via Orianna; routes through Sonnet executors." \
  0

# Pass case 4: Anthropic's API — possessive technical reference
run_xfail "QA-P4: Anthropic's tool-use API — possessive technical ref must pass" \
  "chore: update client

Anthropic's tool-use API supports streaming." \
  0

# Pass case 5: bare "the Claude CLI" mention — no attribution verb
run_xfail "QA-P5: the Claude CLI mention — no attribution verb, must pass" \
  "fix: handle prompt

The Claude CLI prompts for confirmation." \
  0

# Pass case 6: Human-Verified: yes alone with clean message — must pass (trailer is inert)
# xfail because pre-T2 the override exits 0, post-T2 it's also 0 (trailer is harmless inert text)
# This case should already pass today, but adding as explicit assertion.
run_case "QA-P6: Human-Verified: yes with clean message — trailer is inert, must pass" \
  "chore: pair session

Human-Verified: yes" \
  0

# --- Override-no-op regression cases (plan: no-ai-attribution-detector-tightening) ---
# Cases 11-12: after T2, Human-Verified: yes must NOT unblock attribution markers.

# Case 11: attribution phrase + Human-Verified: yes → still blocks after T2
run_xfail "QA-C11: Generated by Claude + Human-Verified: yes — override removed, must still block" \
  "chore: some work

Generated by Claude
Human-Verified: yes" \
  1

# Case 12: Co-Authored-By + Human-Verified: yes → still blocks after T2
run_xfail "QA-C12: Co-Authored-By + Human-Verified: yes — override removed, must still block" \
  "chore: some work

Co-Authored-By: Foo <a@b>
Human-Verified: yes" \
  1

# --- Summary ---

printf '\nT3+T1ext: %d passed, %d failed, %d xfail (expected before impl)\n' "$pass" "$fail" "$xfail"
if [ "$fail" -gt 0 ]; then
  exit 1
fi
exit 0
