#!/usr/bin/env bash
# scripts/hooks/commit-msg-no-ai-coauthor.sh
# commit-msg hook: rejects commits whose message contains AI attribution or
# Co-Authored-By trailers of any kind.
#
# Installed via: scripts/install-hooks.sh (commit-msg dispatcher)
# Plans:
#   plans/in-progress/personal/2026-04-21-commit-msg-no-ai-coauthor-hook.md
#   plans/approved/personal/2026-04-25-no-ai-attribution-defense-in-depth.md
#   plans/approved/personal/2026-04-26-no-ai-attribution-detector-tightening.md
#
# Rules:
#   "Never include AI authoring references in commits" (global CLAUDE.md)
#   "Never write any Co-Authored-By: trailer" (_shared/no-ai-attribution.md)
#
# Rejection patterns:
#   PATTERN_A: ANY Co-Authored-By: trailer (universal block)
#   PATTERN_B: AI email domains (belt-and-suspenders)
#   PATTERN_C-verbatim: robot emoji, "Generated with [Claude Code]",
#                        "claude.com/code", "AI-generated"
#   PATTERN_C-phrase: attribution phrases — verb + model name
#                     e.g. "Generated by Claude", "Authored by Sonnet"
#   PATTERN_C-trailing: trailing attribution — "by Claude" / "by Anthropic"
#                       at end-of-line or before punctuation
#
# Bare technical mentions of model names (e.g. "opus model tier", "Sonnet executor")
# are allowed — only attribution-context phrases are blocked.
#
# No override mechanism. Human-Verified: yes is inert text (ignored).
#
# Exit codes:
#   0 — message is clean
#   1 — violation detected; message printed to stderr

set -uo pipefail

COMMIT_MSG_FILE="${1:-}"

if [ -z "$COMMIT_MSG_FILE" ]; then
  printf 'commit-msg-no-ai-coauthor.sh: missing argument (path to COMMIT_EDITMSG)\n' >&2
  exit 1
fi

if [ ! -f "$COMMIT_MSG_FILE" ]; then
  printf 'commit-msg-no-ai-coauthor.sh: file not found: %s\n' "$COMMIT_MSG_FILE" >&2
  exit 1
fi

offending=""

# --- Pattern A: ANY Co-Authored-By: trailer (universal block) ---
coauthor_lines="$(grep -iE '^Co-Authored-By:' "$COMMIT_MSG_FILE" 2>/dev/null || true)"
if [ -n "$coauthor_lines" ]; then
  offending="$offending
$coauthor_lines"
fi

# --- Pattern B: AI-associated email domain (belt-and-suspenders) ---
domain_lines="$(grep -iE '@(anthropic\.com|claude\.com|noreply\.anthropic\.com)' "$COMMIT_MSG_FILE" 2>/dev/null || true)"
if [ -n "$domain_lines" ]; then
  offending="$offending
$domain_lines"
fi

# --- Pattern C-verbatim: unambiguous verbatim markers ---
# Tightened: claude.com -> claude\.com/code (avoids false positives on bare claude.com docs links)
verbatim_lines="$(grep -iE '🤖|Generated with \[Claude Code\]|claude\.com/code|AI-generated' "$COMMIT_MSG_FILE" 2>/dev/null || true)"
if [ -n "$verbatim_lines" ]; then
  offending="$offending
$verbatim_lines"
fi

# --- Pattern C-phrase: attribution-phrase regexes ---
# Verb + model name (case-insensitive verb, any-case model token).
# Matches: Generated by Claude, Authored by Sonnet, Written by Anthropic,
#          Co-authored by Opus, Coauthored by Haiku, etc.
phrase_lines="$(grep -iE '(Generated|Authored|Written|Co-authored|Coauthored)[[:space:]]+by[[:space:]]+(Claude|Anthropic|Sonnet|Opus|Haiku)' "$COMMIT_MSG_FILE" 2>/dev/null || true)"
if [ -n "$phrase_lines" ]; then
  offending="$offending
$phrase_lines"
fi

# --- Pattern C-trailing: narrow trailing-attribution form ---
# Matches: "by Claude" / "by Anthropic" at end-of-line or before .,;
# Requires whitespace/punct before "by" to avoid mid-sentence false positives.
trailing_lines="$(grep -iE '(^|[[:space:]])[Bb]y[[:space:]]+(Claude|Anthropic)([[:space:]]*[.,;]|[[:space:]]*$)' "$COMMIT_MSG_FILE" 2>/dev/null || true)"
if [ -n "$trailing_lines" ]; then
  offending="$offending
$trailing_lines"
fi

# Deduplicate and strip leading blank line from concatenation
offending="$(printf '%s\n' "$offending" | grep -v '^[[:space:]]*$' | sort -u || true)"

if [ -z "$offending" ]; then
  exit 0
fi

printf '\n\342\234\230 AI attribution or Co-Authored-By trailer detected in commit message:\n' >&2
while IFS= read -r line; do
  [ -n "$line" ] && printf '    %s\n' "$line" >&2
done <<EOF
$offending
EOF

cat >&2 <<'REJECTION'

Per global CLAUDE.md and _shared/no-ai-attribution.md:
  - Never write any Co-Authored-By: trailer (universal block).
  - Never write AI attribution phrases: "Generated by Claude", "Authored by Sonnet",
    "Written by Anthropic", "Co-authored by Opus", "by Claude", etc.
  - Never write: AI-generated, 🤖, "Generated with [Claude Code]", claude.com/code.
    (Non-exhaustive — when in doubt, omit attribution.)

Bare technical mentions of model names are allowed.
Remove the offending attribution content and retry.
REJECTION

exit 1
